# Generated by Django 4.2.3 on 2023-07-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_url', models.CharField(max_length=100)),
                ('shorturl', models.CharField(max_length=100)),
            ],
        ),
    ]
